### PR TITLE
[CI][GH-ACTION]: Migration to gh-action as CI tool

### PR DESCRIPTION
**Pull request by anshulsahni**
Fixes: https://github.com/adamzolyak/monorepo-pr-labeler-action/issues/18
	- Wrote a validate.yaml as workflow for running unit tests
	- Ugraded to NodeJS v14 in Dockerfile
	- Introduced eslint in the code for linting the source code

### CODE REVIEW

**Comment by anshulsahni** [comment]
@adamzolyak Raised PR for integrating gh actions as CI & also upgraded the node version to 14 in Dockerfile, please check this PR

**Comment by anshulsahni** [comment]
@adamzolyak did you get a chance to have a look at this?

**Comment by anshulsahni** [comment]
@adamzolyak did you get a chance to take a look at this?

**Comment by adamzolyak** [comment]
@anshulsahni thanks for your contribution!  Sorry, I've been on a trip for a few weeks and away from my computer.  Would you be willing to update the change to not include the semi rule?  If you think there's value in switching, I'd prefer a separate PR to make this change easier to review.  What process would you suggest for testing this PR?

**Comment by anshulsahni** [comment]
HI @adamzolyak, welcome back,

**Comment by anshulsahni** [comment]
Hi @adamzolyak, welcome back, yeah having a separate PR to switch CI & a separate one to change eslint rule would make sense.

Testing this PR I'm not really very sure but you can check actions run here in my forked repo from where the PR is raised :point_down: 
https://github.com/anshulsahni/monorepo-pr-labeler-action/actions/

**Comment by adamzolyak** [comment]
Awesome. I’ll try to get this reviewed and merged this week. This is the last week of my travel but I should have some time to work on it. I’ll also try to get the repo migrated next week so that you can be a co maintainer. 🙌

-Adam

**Comment by anshulsahni** [comment]
Hi @adamzolyak, hope your vacation was awesome 

Here as advised by you have done the changes, eslint configuration & fixes related to the linting errors are now in a separate branch, will file a separate PR for that

Please review these changes

**Review by adamzolyak — APPROVED** [review]

**Pull request merged**
